### ISSUE TITLE
cannot find authorization end point on https://xam.dk

### ISSUE THREAD

**Issue by maxandersen** [aaronpk/Quill#106]
I have a verbatim copy of `<link rel="authorization_endpoint" href="https://indieauth.com/auth">` on https://xam.dk in `<head>` but I still gets told quill can't find my endpoint.

Anyway to get info on what quill actually finds/reads from xam.dk ?

**Comment by aaronpk** [comment]
I just tried reproducing this and Quill seems to find it just fine. I did notice that it takes a couple seconds for the site to respond, so if that was taking much longer at some point then it's possible Quill was timing out.

**Comment by maxandersen** [comment]
it started working without changing things - I guess quill caches site info it read at least 30 minutes or more ? 

in any case it works now - thanks :)

**Comment by maxandersen** [comment]
found out my ISP actually have an additional varnish cache in front which would explain why it could take even longer than expected to see updates. closing after I now are able to purge and disable that cache if need be.
