### ISSUE TITLE
POSTing duplicate images?

### ISSUE THREAD

**Issue by skpy** [aaronpk/Quill#107]
Testing Quill against [my Micropub](https://github.com/skpy/micropub) endpoint, I seem to be getting duplicate image uploads.  I believe my Media Endpoint support is working, as evidenced by the fact that I get media uploads, but I get **two** uploads for each one.

I added this simple debug code to my micropub's index.php:
```
    file_put_contents($config['base_path'] . 'debug.txt', print_r($_POST,true) . "\n" . print_r($_FILES, true), FILE_APPEND);
```

I then made sure that `debug.txt` was present, owned by the web server user, and empty:
```
sudo rm -f debug.txt
sudo -u www-data touch debug.txt
```

When I next uploaded an image, this is what I captured:
```
Array
(
)

Array
(
    [file] => Array
        (
            [name] => IMG_0293.jpg
            [type] => image/jpeg
            [tmp_name] => /tmp/phpIfmgHF
            [error] => 0
            [size] => 3808859
        )

)
Array
(
    [h] => entry
    [access_token] => [...elided...]
    [content] => ffffffffff
)

Array
(
    [photo] => Array
        (
            [name] => IMG_0293.jpg
            [type] => image/jpeg
            [tmp_name] => /tmp/phpnFGKen
            [error] => 0
            [size] => 3808859
        )

)
```

According to the Quill docs, "If you have a Media Endpoint, then you'll always get a form-encoded request with the URL of any photos."

I'm perfectly willing to believe that I've done something dumb within my own code, but it's not immediately clear to me where or how, given the debug output above showing duplicate $_FILE values.

**Comment by aaronpk** [comment]
The media endpoint needs to return the proper response in order to tell Quill that it worked, otherwise Quill treats it as a failure and will then upload using the fallback method.

Double check that the media endpoint is returning HTTP 201 *and* the `Location` header with the full URL to the file.

https://www.w3.org/TR/micropub/#response-3

**Comment by skpy** [comment]
I believe it to be the case that I am doing those things.

https://github.com/skpy/micropub/blob/master/index.php#L74-L77

My server logs suggest that I am doing this correctly:
```
173.230.155.197 - - [03/Jan/2019:22:22:39 -0500] "POST /micropub/index.php HTTP/1.1" 201 72
65.60.241.209 - - [03/Jan/2019:22:22:39 -0500] "GET /images/2019/01/IMG_0293-849280.jpeg HTTP/2.0" 200 217441
173.230.155.197 - - [03/Jan/2019:22:22:45 -0500] "POST /micropub/index.php HTTP/1.1" 201 0
65.60.241.209 - - [03/Jan/2019:22:22:45 -0500] "GET /2019/01/ HTTP/2.0" 200 915
```

**Comment by skpy** [comment]
Turns out I was being impatient.  My endpoint was busy resizing the image, but I wasn't waiting long enough. Before Quill got the response, I clicked the "add" button and went back to the note editor.

If I wait to click "add" until the photo displays its final URL, I then only get one photo upload!
