### ISSUE TITLE
Quill keeps last draft and more than 1 image in it's editor

### ISSUE THREAD

**Issue by frankmeeuwsen** [aaronpk/Quill#109]
More than once Quill remembers the post I was working on and keeps this post as a draft in the editor when I want to make a new post. Also, it shows by default the last uploaded image to my website. Even when the upload date is several days ago.
I expect the Quill editor to be empty when I open it from my browser bookmarksbar and not have old drafts already in the textfield. I have to manually remove all this text and images before I can actually make a post, which slows down the ease of posting something through Quill.

**Comment by aaronpk** [comment]
I've noticed this too, it's not clearing out the draft post quickly enough or something. It's not consistent so it's hard to test, but I've pushed a fix that I think will solve it. Let me know if you continue to see problems.

**Comment by frankmeeuwsen** [comment]
After a few tests the last days I haven't seen this behaviour so it looks like it's fixed.
