### ISSUE TITLE
add image-option to note editor

### ISSUE THREAD

**Issue by diplix** [aaronpk/Quill#12]
it would be nice to have an optional form field in the note editor for an image (or serveral images) that will be send as file via post to the micropub-endpoint.

**Comment by aaronpk** [comment]
You can already add images by clicking the little "+" button to the left of the writing area. Would that accomplish what you're trying to do?

**Comment by diplix** [comment]
yeah, i saw that in the medium-style editor. but i’d love to have that option in the note editor.

btw.: the medium-style editor is great, but i don’t know what to make of those base64 encoded images. my cms (and browser) can’t handle megabytes of editor form content, so i’d have to use some means to save those images to a file. but it looks great, works and seems very promising, too.

**Comment by aaronpk** [comment]
oh! gotcha, totally missed that. It's been a long day.

Yeah it'd be nice to have a photo upload option on the note editor.

**Comment by aaronpk** [comment]
@Jeena added a new "photo" form for posting photos from Quill!
