### ISSUE TITLE
Show syndication options for repost and favorite

### ISSUE THREAD

**Issue by gijswijs** [aaronpk/Quill#136]
Show syndication options for repost and favorite [](https://brid.gy/publish/github)

(Originally published at: https://www.gijsvandam.nl/reply/2021/04/14-33126)

**Comment by gijswijs** [comment]
I am using Quill (and/or Monocle) for posting Notes and syndicating them to Twitter and/or Mastodon.

I also want to favorite (like) tweets and I would like to see my likes syndicated to Twitter (or Mastodon in case of toots).

But Quill doesn't show the syndication targets for favorites and reposts. Would be nice to see them there too. [](https://brid.gy/publish/github)

**Comment by aaronpk** [comment]
Closing since Twitter is dead
