### ISSUE TITLE
PHP error on my own instance

### ISSUE THREAD

**Issue by fkooman** [aaronpk/Quill#14]
Hi,

I managed to install it no my own machine, and I get really far, token fetching and everything works, until I reach the `/new` URL before trying to publish something at the bottom of the page. It seems to prevent posting something...

```
Type: ErrorException
Code: 8
Message: Undefined property: Savant3::$authorizing
File: /var/www/Quill/views/layout.php
Line: 78
```

**Comment by aaronpk** [comment]
Thanks, this has been fixed in #21
