### ISSUE TITLE
Converting image buffer to base64?

### ISSUE THREAD

**Issue by gijswijs** [aaronpk/Quill#141]
Since I don't use a media endpoint, the photo's I upload using quill get posted to my micropub server inline. My micropub server accepts json, so it receives something like this:

```
files:
   [ { filename:
        '_src/stream/media/2022/02/15-32499/imagefile.jpg',
       buffer:
        <Buffer ef bf bd ef bf bd ef bf bd ef bf bd 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ef bf bd ef bf bd 00 43 00 06 04 05 06 05 04 06 06 05 06 07 07 06 ... > } ]
```
I commit the buffer directly to a github repo, using the github API. Using Node.JS this looks something like this:

```javascript
return octokit.request(
                "PUT /repos/{owner}/{repo}/contents/{path}",
                {
                  owner: user,
                  repo: repo,
                  path: file.filename,
                  message: "micropub image for a " + postType,
                  content: file.buffer.toString("base64"),
                }
              );
```

But that results in files like [this](https://github.com/gijswijs/gijswijs.github.io/blob/7cf7c2145398b6b6a0ed78e601cd5c0e568b74d6/stream/2022/02/15-47823/prikkie.jpg). I fear there is some file encoding issue at play here, but I can't figure it out.

**Comment by gijswijs** [comment]
This ended up to be way more work than expected. As it turns out, Quill sends an extra two bytes in the multipart/form-data. It starts with a carriage return and a linefeed that end up as the first two bytes in the buffer. Those two bytes mess up the encoding.

My local testing with Postman does not include those two bytes if I send the same image. So this was a hard bug to track down.

To fix this I check if the first two bytes are CRLF and if so I take the subarray of the buffer starting at 2.

```javascript
const compare = Buffer.from("\r\n");
if (file.buffer.compare(compare, 0, 2, 0, 2) === 0) {
  file.buffer= file.buffer.subarray(2);
}
```

Not sure whether this is a Quill issue, so for now I will close it.

**Comment by aaronpk** [comment]
This is really strange. Multipart encoding is supposed to have two sequences of crlf. It sounds like Postman isn't sending it correctly in your example. Are you sure you're using the actual file upload method in Postman and not a generic HTTP Post? 

It sounds like the framework you're using isn't properly handling multipart encoding.

do either of these sound like they might be the right direction?

**Comment by gijswijs** [comment]
> Are you sure you're using the actual file upload method in Postman and not a generic HTTP Post?

Yes, I'm certain.

The only thing I can think of is Azure Functions doing something weird on their side. I think they use a custom build of express.js under the hood of their NodeJS offering, but I'm not sure. I didn't have time to look into it any deeper, but when I do, I'll make sure to report back.
