### ISSUE TITLE
Add image to a note, and it gets submitted to the media endpoint (expected) AND included in the eventual micropub POST request (unexpected)

### ISSUE THREAD

**Issue by rosskarchner** [aaronpk/Quill#144]
I would have expected it to be one or the other, not both. Is this intentional behavior? If not, how can I help troubleshoot?

**Comment by aaronpk** [comment]
I'm guessing it's not getting the right response from the media endpoint so it thinks it failed. Do you see a URL from your media endpoint after uploading the image?

**Comment by rosskarchner** [comment]
aha-- I opened up the javascript console and see a "no Location header in response" error. That gives me something to look at, Thanks!

**Comment by rosskarchner** [comment]
OK, here's a question then: is 'Location' case-sensitive? In Postman I can see that it's return the header as lower-case 'location' (even though my code says 'Location'). 

This might be a quirk of AWS Lambda/API Gateway.

**Comment by aaronpk** [comment]
Excellent, thanks for the nudge!
