### ISSUE TITLE
Add a param for in-reply-to

### ISSUE THREAD

**Issue by ShaneHudson** [aaronpk/Quill#17]
By using ?url= or similar, it allows us to create applications that send replies using Quill as a micropub client. My specific use-case is an app for android that adds to the Twitter's share menu.

**Comment by voxpelli** [comment]
Would make it possible to set Quill up to handle many of the WebActions through eg. indie-config as well, http://indiewebcamp.com/indie-config

**Comment by kylewm** [comment]
@ShaneHudson this was added a while ago `?reply=` https://github.com/aaronpk/Quill/pull/5

**Comment by aaronpk** [comment]
Yep thanks @kylewm!
