### ISSUE TITLE
Send HTML content in an object instead of string

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Quill#27]
See http://indiewebcamp.com/Micropub-brainstorming#HTML_Escaping for background.

The HTML editor will send content as:

```
content[html]=html content here
```

This should be an opt-in change with a banner notice the same way I did with OwnYourGram.

**Comment by voxpelli** [comment]
For future reference: Updated my endpoint to support this: https://github.com/voxpelli/node-format-microformat/commit/962e66a89533f614a5b6f2583d8480157847da29

**Comment by aaronpk** [comment]
This is live now! There's a notice that appears on the editor until you opt in to the change.

![quill editor](https://cloud.githubusercontent.com/assets/113001/9765975/9d5cf55c-56cb-11e5-92a5-8f2f232e50fe.png)
