### ISSUE TITLE
support identity URLs with non-trivial paths

### ISSUE THREAD

**Issue by kylewm** [aaronpk/Quill#28]
I think just this check needs to change to support paths:

https://github.com/aaronpk/Quill/blob/master/controllers/auth.php#L46

Related: https://github.com/indieweb/indieauth-client-php/issues/4

**Comment by snarfed** [comment]
one example user request: https://wordpress.org/support/topic/any-chance-of-a-tutorial#post-7352513

**Comment by aaronpk** [comment]
Thanks! This is all fixed and I was able to test it from silo.pub!

**Comment by kylewm** [comment]
Yay!
