### ISSUE TITLE
Use php array syntax instead of comma-separated list

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Quill#3]
We're updating the micropub spec to use array syntax instead of comma-separated lists when needing to specify multiple values. Quill will need to be updated to send the syndicate-to parameter as an array (syndicate-to[]=twitter) rather than comma-separated list.

**Comment by voxpelli** [comment]
The same needs to happen for `category` – it sends a comma separated list there as well.

**Comment by aaronpk** [comment]
@kylewm pointed me to this library so I can use it for tags http://aehlke.github.io/tag-it/

**Comment by aaronpk** [comment]
This is done now, but I'm going to make a new issue to improve the tag interface with that library.
