### ISSUE TITLE
Support syndication targets in JSON format

### ISSUE THREAD

**Issue by barryf** [aaronpk/Quill#36]
Now that the Micropub spec enforces the syndication target list in JSON format, Quill should support JSON and probably also allow for old style comma-separated or array lists for those who have yet to transition.

http://www.w3.org/TR/micropub/#syndication-targets

**Comment by aaronpk** [comment]
Thanks! We're also working on some enhancements to the JSON response so that clients can provide a better UI.

**Comment by barryf** [comment]
Nice. I saw the changes in IRC and your new Micropub draft so have updated my software to match. Quill and Woodwind are now successfully displaying the `uid` and `name` of my targets. I've also updated Micropublish.

**Comment by aaronpk** [comment]
@barryf awesome! Any chance you can hop in IRC? I'd love to ask you a few questions about your implementation.
