### ISSUE TITLE
Add a loading indicator

### ISSUE THREAD

**Issue by voxpelli** [aaronpk/Quill#42]
As my micropub endpoint is hosted on a free Heroku account currently it's startup time can be fairly slow if I haven't posted in a while so it can take a few seconds for it to finish and right now Quill gives no feedback that it has actually started to process my request (at least not when I'm adding a like).

Would be a neater experience if it added some kind of loading indicator :)

**Comment by aaronpk** [comment]
@adactio just posted a neat bit of JS that I plan on adapting for this purpose: https://adactio.com/journal/10728

**Comment by aaronpk** [comment]
Quick fix was to do the same thing that I did on the new post screen, changing the button to "Working" after it's clicked.
