### ISSUE TITLE
error on returning from authentication at hosted known

### ISSUE THREAD

**Issue by kevinmarks** [aaronpk/Quill#47]
I tried to log in using known.kevinmarks.com, and got the following error after being redirected back to quill:

Slim Application Error
The application could not run because of the following error:

Details

Type: ErrorException
Code: 2
Message: array_key_exists() expects parameter 2 to be array, string given
File: /web/sites/quill.p3k.io/lib/helpers.php
Line: 208
Trace
#0 [internal function]: Slim\Slim::handleErrors(2, 'array_key_exist...', '/web/sites/quil...', 208, Array)
#1 /web/sites/quill.p3k.io/lib/helpers.php(208): array_key_exists('service', 'twitter::kevinm...')
#2 /web/sites/quill.p3k.io/controllers/auth.php(217): get_syndication_targets(Object(ORM))
#3 [internal function]: {closure}()
#4 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Router.php(172): call_user_func_array(Object(Closure), Array)
#5 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Slim.php(1222): Slim\Router->dispatch(Object(Slim\Route))
#6 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#7 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#8 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#9 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Slim.php(1174): Slim\Middleware\PrettyExceptions->call()
#10 /web/sites/quill.p3k.io/public/index.php(23): Slim\Slim->run()
#11 {main}

**Comment by snarfed** [comment]
i just saw this too, against https://snarfed.org/w/?micropub=endpoint , which runs https://github.com/snarfed/wordpress-micropub .

it responds to both `q=syndicate-to` and `q=config` with `{"syndicate-to":[]}`.

**Comment by snarfed** [comment]
oh, actually mine is similar but not exactly the same.

```
Details
Type: ErrorException
Code: 2
Message: array_key_exists() expects parameter 2 to be array, string given
File: /web/sites/quill.p3k.io/lib/helpers.php
Line: 214
Trace

#0 [internal function]: Slim\Slim::handleErrors(2, 'array_key_exist...', '/web/sites/quil...', 214, Array)
#1 /web/sites/quill.p3k.io/lib/helpers.php(214): array_key_exists('syndicate-to', 'missing access ...')
#2 /web/sites/quill.p3k.io/controllers/auth.php(217): get_micropub_config(Object(ORM))
#3 [internal function]: {closure}()
#4 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Router.php(172): call_user_func_array(Object(Closure), Array)
#5 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Slim.php(1222): Slim\Router->dispatch(Object(Slim\Route))
#6 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#7 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#8 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#9 /web/sites/quill.p3k.io/vendor/slim/slim/Slim/Slim.php(1174): Slim\Middleware\PrettyExceptions->call()
#10 /web/sites/quill.p3k.io/public/index.php(23): Slim\Slim->run()
#11 {main}
```
