### ISSUE TITLE
Quill keeps logging me out

### ISSUE THREAD

**Issue by sebsel** [aaronpk/Quill#65]
I have a feeling Quill is logging me out faster than before. First it had a cookie, and now it's only a session, it feels like.

Should these two have the same name?
https://github.com/aaronpk/Quill/blob/master/public/index.php#L20
https://github.com/aaronpk/Quill/blob/master/controllers/controllers.php#L28

**Comment by aaronpk** [comment]
Hm yes I've noticed this too. Ill go back and see what i changed recently that could have caused this

**Comment by sebsel** [comment]
I think it was around the time you made the reply-context.
This one looks suspicious:
https://github.com/aaronpk/Quill/commit/263893952c7f9f690ad1625dc874e5d5ba35111c

**Comment by aaronpk** [comment]
ah I figured it out. I had upgraded the PHP version on the server recently, and they changed where all the config files live, so I'm still piecing back together my php.ini settings. Should be fixed now!

**Comment by sebsel** [comment]
I'm still logged in! :D
