### ISSUE TITLE
figure, figcaption markup missing for captioned images in Editor

### ISSUE THREAD

**Issue by martymcguire** [aaronpk/Quill#68]
I made a post with an image and an embedded caption. Instead of the expected `<figure><img /><figcaption>CAPTION HERE</figcaption></figure>` markup around the inserted image and the caption, it became `<img /> CAPTION HERE`.

I think this was introduced by #67 ?

**Comment by aaronpk** [comment]
ah yeah, I need to whitelist those two tags.
