### ISSUE TITLE
Support RSVP

### ISSUE THREAD

**Issue by sebsel** [aaronpk/Quill#71]
I've been posting RSVP's via other ways, but it would be really nice if Quill supported them too.

It could be a separate view, like /favorite or /bookmark, but since an RSVP is just a `in-reply-to` with an `rsvp` field, it could also just come from the note section /new.

Got a little carried away with my mockup in macOS Preview:
![rsvp](https://cloud.githubusercontent.com/assets/16517999/23812599/7adf6152-05db-11e7-9530-ecd1c90d79c6.jpg)

This would also mean that the preview should detect the post replying to is an event, but it already does detect entries, it seems, because the preview fails for events at the moment.

**Comment by aaronpk** [comment]
This is a great idea
