### ISSUE TITLE
Outdated docs for HTML posts

### ISSUE THREAD

**Issue by sknebel** [aaronpk/Quill#72]
https://quill.p3k.io/docs/editor still describes posts with HTML content being created using form-encoded requests, while Quill actually (spec-conforming) uses JSON-encoding for them.

/cc @eli-oat

**Comment by eli-oat** [comment]
Once (if?) I wrap my head around micropub's intricacies, I'd love to help update this documentation.

**Comment by aaronpk** [comment]
Thanks for finding that! I've updated the docs.
