### ISSUE TITLE
Detects $me as endpoint when not found

### ISSUE THREAD

**Issue by sebsel** [aaronpk/Quill#78]
On https://github.com/aaronpk/Quill/blob/master/controllers/auth.php#L32 and 
https://github.com/aaronpk/Quill/blob/master/controllers/auth.php#L188, `IndieAuth\Client::discoverAuthorizationEndpoint()` and `Mf2\resolveUrl()` are chained together. if the discovery returns `false`, resolveUrl resolves that to the root of the given URL, so `$me`.

```
  $authorizationEndpoint = Mf2\resolveUrl($me, IndieAuth\Client::discoverAuthorizationEndpoint($me));
```

Might also be a problem of Mf2\resolveUrl(). Should that return `false` when given `false` instead of `''` or `'/'`?

**Comment by aaronpk** [comment]
Thanks, I added that during indieweb summit pretty quickly. I'm actually going to solve this in the indieauth client library.
