### ISSUE TITLE
Don't rely on `me` in the callback URL

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Quill#79]
should get the `me` from the session to avoid being tricked into exchanging the auth code at some other server

**Comment by cweiske** [comment]
This breaks commentpara.de, which hands out different user URLs depending on their login.

**Comment by aaronpk** [comment]
@cweiske This is just about not using the `me` returned in the *callback URL*. Quill still uses the `me` returned from the POST request that gets an access token. It looks like commentpara.de is returning `me=https://commentpara.de/` in the response but it should actually return the unique user URL for the user who logged in.

**Comment by cweiske** [comment]
For reference: Taking "me" from the callback is not secure because the user could change that.
