### ISSUE TITLE
Prefil Quill note image from wordpress media endpoint

### ISSUE THREAD

**Issue by dougbeal** [aaronpk/Quill#98]
[Quill doesn’t understand WordPress media endpoint yo prefill latest image](https://github.com/aaronpk/Quill/issues)

# Prefil Quill note image from weird press media endpoint

http://dougbeal.com/wp-json/wp/v2/media

(Originally published at: https://crw.moe/b/QH)

**Comment by aaronpk** [comment]
This doesn't look like the Micropub Media Endpoint standard. @GWG was working on building in a Micropub Media Endpoint into the Micropub plugin, at which point this should work.

**Comment by dshanske** [comment]
It's near release. That's the rest API media endpoint

**Comment by dougbeal** [comment]
@dshanske should this work now?

**Comment by dougbeal** [comment]
It works! Last upload image shows up automatically now in Quill!
